import path from "path";
import { fileURLToPath } from "url";
import fs from "fs";
import renderRulesTableContent from "./render-rules";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// -----------------------------------------------------------------------------
const readmeFilePath = path.resolve(__dirname, "../docs/rules/index.md");
fs.writeFileSync(
  readmeFilePath,
  `---
sidebarDepth: 0
---

# Available Rules

<!-- This file is automatically generated in tools/update-docs-rules-index.ts, do not change! -->

The \`--fix\` option on the [command line](https://eslint.org/docs/user-guide/command-line-interface#fixing-problems) automatically fixes problems reported by rules which have a wrench :wrench: below.  
The rules with the following star :star: are included in \`configs.recommended\` or \`configs.standard\`.
${renderRulesTableContent(1)}`,
);
