import path from "node:path";
import { fileURLToPath } from "node:url";
import fs from "node:fs";
import renderRulesTableContent from "./render-rules.ts";

const filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(filename);

// -----------------------------------------------------------------------------
const readmeFilePath = path.resolve(dirname, "../docs/rules/index.md");
fs.writeFileSync(
  readmeFilePath,
  `---
sidebarDepth: 0
---

# Available Rules

<!-- This file is automatically generated in tools/update-docs-rules-index.ts, do not change! -->

The \`--fix\` option on the [command line](https://eslint.org/docs/user-guide/command-line-interface#fixing-problems) automatically fixes problems reported by rules which have a wrench :wrench: below.  
The rules with the following star :star: are included in \`configs.recommended\` or \`configs.standard\`.
${renderRulesTableContent(1)}`,
);
